/* ============================================================
   Cardio Routine — configuration
   ------------------------------------------------------------
   THESE STAY BLANK. Do not paste your Apps Script URL here.

   GitHub Pages needs a public repo on the free tier, and public
   repos are continuously scraped by bots hunting for endpoints
   and credentials. Anything committed to this file is published
   to the world and to anyone who views source on the live site.

   Sync is configured ON THE DEVICE instead:
     Settings → Sheet sync → paste the URL and token → Save
   or open a one-time setup link generated by "Copy setup link".
   Either way it is stored in that browser's localStorage and
   never appears in this repo or in the page source.

   The fields below exist only as a fallback for a PRIVATE
   deployment where hardcoding is safe. Leave them empty here.
   ============================================================ */

window.CARDIO_CONFIG = {
  syncUrl: '',
  syncToken: '',
  appVersion: '1.2.1'
};
